Repository facebook/zstd, pull requests merged in 2019-09, with the labels that each got.

#1769 Fix streaming compression/decompression examples
  examples/streaming_compression.c
  examples/streaming_decompression.c
Labels: CLA Signed

#1770 Single file decoder correctness and tidy
  contrib/single_file_decoder/README.md
  contrib/single_file_decoder/build_test.sh
  contrib/single_file_decoder/combine.sh
  contrib/single_file_decoder/examples/README.md
  contrib/single_file_decoder/examples/emscripten.c
  contrib/single_file_decoder/examples/simple.c
  contrib/single_file_decoder/examples/testcard.png
Labels: CLA Signed

#1771 Passing ZSTD_CCtx_params by const pointer
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstdmt_compress.c
Labels: CLA Signed

#1773 Removing redundant condition in decompression, making first block rle…
  lib/compress/zstd_compress.c
  programs/fileio.c
  tests/golden-compression/huffman-compressed-larger
  tests/golden-decompression/rle-first-block.zst
  tests/playTests.sh
Labels: CLA Signed

#1777 [Fuzz] Improve data generation #1723
  tests/fuzz/Makefile
  tests/fuzz/README.md
  tests/fuzz/fuzz_data_producer.c
  tests/fuzz/fuzz_data_producer.h
  tests/fuzz/simple_decompress.c
Labels: CLA Signed

#1775 fix educational decoder
  Makefile
  doc/educational_decoder/Makefile
  doc/educational_decoder/harness.c
  doc/educational_decoder/zstd_decompress.c
  doc/educational_decoder/zstd_decompress.h
  lib/dictBuilder/cover.c
Labels: CLA Signed

#1712 Allocate Internal Buffers via Workspace Abstraction
  build/VS2008/fullbench/fullbench.vcproj
  build/VS2008/fuzzer/fuzzer.vcproj
  build/VS2008/zstd/zstd.vcproj
  build/VS2008/zstdlib/zstdlib.vcproj
  build/VS2010/fullbench/fullbench.vcxproj
  build/VS2010/fuzzer/fuzzer.vcxproj
  build/VS2010/libzstd-dll/libzstd-dll.vcxproj
  build/VS2010/libzstd/libzstd.vcxproj
  build/VS2010/zstd/zstd.vcxproj
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_compress_literals.c
  lib/compress/zstd_compress_literals.h
  lib/compress/zstd_compress_sequences.c
  lib/compress/zstd_compress_sequences.h
  lib/compress/zstd_cwksp.h
Labels: CLA Signed

#1788 Add Crystal Lang Binding Reference to Homepage
  index.html
Labels: CLA Signed

#1789 [fuzz] Fix leak in block_round_trip
  tests/fuzz/block_round_trip.c
Labels: CLA Signed

#1791 [libzstd] Improve advanced API docs
  lib/zstd.h
Labels: CLA Signed

#1780 Avoid Clearing Tables Even When Changing CParams
  lib/common/mem.h
  lib/compress/zstd_compress.c
  lib/compress/zstd_cwksp.h
  tests/fuzzer.c
Labels: CLA Signed, enhancement, optimization

#1783 Set Mod Time Nanoseconds
  programs/util.c
Labels: CLA Signed

#1798 minor refactor of ZSTD_fast
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_fast.c
Labels: CLA Signed

#1756 Improvements in zstd decode performance
  lib/common/zstd_internal.h
  lib/compress/zstd_compress_internal.h
  lib/decompress/zstd_decompress_block.c
Labels: CLA Signed

#1802 Adding 4 blocks to FSE_BLOCKBOUND() in lib/common (different from las…
  lib/common/fse.h
Labels: CLA Signed

#1801 [test] Test the bounds of ZSTD_c_srcSizeHint
  tests/zstreamtest.c
Labels: CLA Signed

#1806 Update Comment on `ZSTD_estimateCCtxSize()`
  lib/zstd.h
  tests/fuzzer.c
Labels: CLA Signed

#1804 Optimize (de)compression and fix wildcopy overread
  lib/common/compiler.h
  lib/common/zstd_internal.h
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_double_fast.c
  lib/compress/zstd_fast.c
  lib/compress/zstd_lazy.c
  lib/compress/zstd_ldm.c
  lib/compress/zstd_opt.c
  lib/decompress/zstd_decompress_block.c
  tests/decodecorpus.c
Labels: CLA Signed

#1808 Improve ZSTD_highbit32's codegen
  lib/common/bitstream.h
  lib/common/zstd_internal.h
  lib/legacy/zstd_v01.c
  lib/legacy/zstd_v02.c
  lib/legacy/zstd_v03.c
  lib/legacy/zstd_v04.c
  lib/legacy/zstd_v05.c
  lib/legacy/zstd_v06.c
  lib/legacy/zstd_v07.c
Labels: CLA Signed, optimization
