Repository facebook/zstd, pull requests merged in 2020-05, with the labels that each got.

#2101 [build] fix meson build issue
  build/meson/meson.build
Labels: CLA Signed

#2100 Fix up superblock mode
  lib/common/huf.h
  lib/common/zstd_internal.h
  lib/compress/huf_compress.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_compress_literals.c
  lib/compress/zstd_compress_superblock.c
  lib/compress/zstd_compress_superblock.h
  lib/compress/zstd_opt.c
  tests/fuzz/simple_round_trip.c
  tests/fuzzer.c
Labels: CLA Signed

#1984 Reduce stack usage of HUF_sort()
  lib/common/huf.h
  lib/compress/huf_compress.c
  tests/decodecorpus.c
Labels: CLA Signed

#2099 Compile Under `-pedantic -Werror` and `-std=c90`
  .circleci/config.yml
  lib/common/compiler.h
  lib/common/fse_decompress.c
  lib/common/xxhash.c
  lib/common/zstd_internal.h
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_compress_literals.c
  lib/compress/zstd_compress_sequences.c
  lib/compress/zstd_compress_superblock.c
  lib/compress/zstd_cwksp.h
  lib/compress/zstd_opt.c
  lib/compress/zstdmt_compress.c
  lib/decompress/zstd_ddict.c
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_block.c
  lib/legacy/zstd_v01.c
  lib/legacy/zstd_v02.c
  lib/legacy/zstd_v03.c
  lib/legacy/zstd_v04.c
  lib/legacy/zstd_v05.c
  lib/legacy/zstd_v06.c
  lib/legacy/zstd_v07.c
  tests/fuzzer.c
  tests/zstreamtest.c
Labels: CLA Signed, Portability, build issue

#2089 [bench] Extending largeNbDicts to compression
  contrib/largeNbDicts/largeNbDicts.c
Labels: CLA Signed

#1976 Add Minification Variable to `lib/Makefile`
  .travis.yml
  lib/Makefile
  lib/README.md
Labels: CLA Signed, release-blocking

#2106 fix minor conversion warnings in huf_compress.c
  lib/compress/huf_compress.c
Labels: CLA Signed

#2108 some more conversion fixes …
  lib/compress/huf_compress.c
  lib/compress/zstd_compress_sequences.c
Labels: CLA Signed

#2109 faster cygwin test
  appveyor.yml
  build/cmake/tests/CMakeLists.txt
Labels: CLA Signed

#2095 [bugs] zstdgrep/grep inconsistencies
  programs/zstdgrep
  tests/playTests.sh
Labels: CLA Signed

#2103 Migrate Includes to Relative Paths
  contrib/single_file_libs/combine.sh
  contrib/single_file_libs/create_single_file_decoder.sh
  contrib/single_file_libs/create_single_file_library.sh
  contrib/single_file_libs/zstd-in.c
  contrib/single_file_libs/zstddeclib-in.c
  lib/Makefile
  lib/common/pool.h
  lib/common/zstd_internal.h
  lib/compress/fse_compress.c
  lib/compress/hist.c
  lib/compress/huf_compress.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_compress_sequences.h
  lib/compress/zstd_compress_superblock.c
  lib/compress/zstd_compress_superblock.h
  lib/compress/zstd_cwksp.h
  lib/compress/zstd_double_fast.h
  lib/compress/zstd_fast.h
  lib/compress/zstd_ldm.c
  lib/compress/zstd_ldm.h
  lib/compress/zstdmt_compress.c
  lib/compress/zstdmt_compress.h
  lib/decompress/huf_decompress.c
  lib/decompress/zstd_ddict.c
  lib/decompress/zstd_ddict.h
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_block.c
  lib/decompress/zstd_decompress_block.h
  lib/decompress/zstd_decompress_internal.h
  lib/deprecated/zbuff.h
  lib/deprecated/zbuff_common.c
  lib/dictBuilder/cover.c
  lib/dictBuilder/cover.h
  lib/dictBuilder/fastcover.c
  lib/dictBuilder/zdict.c
  lib/legacy/zstd_legacy.h
  lib/legacy/zstd_v01.c
  lib/legacy/zstd_v02.c
  lib/legacy/zstd_v03.c
  lib/legacy/zstd_v04.c
  lib/legacy/zstd_v05.c
  lib/legacy/zstd_v05.h
  lib/legacy/zstd_v06.c
  lib/legacy/zstd_v07.c
  programs/Makefile
  programs/benchzstd.c
  programs/benchzstd.h
  programs/datagen.c
  programs/dibio.c
  programs/dibio.h
  programs/fileio.c
  programs/fileio.h
  programs/util.h
  programs/zstdcli.c
Labels: build issue

#2105 [lib] Fix NULL pointer dereference
  lib/common/xxhash.c
  lib/decompress/zstd_decompress_block.c
  lib/legacy/zstd_v01.c
  lib/legacy/zstd_v02.c
  lib/legacy/zstd_v03.c
  lib/legacy/zstd_v04.c
  lib/legacy/zstd_v05.c
  lib/legacy/zstd_v06.c
  lib/legacy/zstd_v07.c
  tests/fuzz/Makefile
  tests/fuzz/block_decompress.c
  tests/fuzz/block_round_trip.c
  tests/fuzz/dictionary_decompress.c
  tests/fuzz/dictionary_loader.c
  tests/fuzz/dictionary_round_trip.c
  tests/fuzz/fuzz_data_producer.c
  tests/fuzz/fuzz_helpers.c
  tests/fuzz/fuzz_helpers.h
  tests/fuzz/simple_compress.c
  tests/fuzz/simple_decompress.c
  tests/fuzz/simple_round_trip.c
  tests/fuzz/stream_decompress.c
  tests/fuzz/stream_round_trip.c
  tests/fuzz/zstd_frame_info.c
  tests/fuzz/zstd_helpers.c
  tests/fuzzer.c
Labels: CLA Signed

#2115 [doc] Adding static analysis section and note
  CONTRIBUTING.md
Labels: CLA Signed

#2111 [zdict] Stabilize ZDICT_finalizeDictionary()
  lib/dictBuilder/zdict.h
Labels: CLA Signed

#2041 Optimize compression by using neon function.
  lib/common/zstd_internal.h
Labels: CLA Signed

#2112 small speed improvement for strategy fast
  lib/compress/zstd_fast.c
Labels: CLA Signed

#2114 support for verbose make
  lib/Makefile
Labels: CLA Signed

#2119 [build] Adding $TARGET_SYSTEM for cross-compilation Fedora fix
  Makefile
  lib/Makefile
Labels: CLA Signed

#2118 programs/README.md: update help text
  programs/README.md
Labels: CLA Signed

#2078 CMake: Fix DESTDIR installs and the Package Config file
  build/cmake/CMakeLists.txt
  build/cmake/lib/CMakeLists.txt
  build/cmake/lib/config.cmake.in
  build/cmake/zstdConfig.cmake
Labels: CLA Signed

#2116 Fix pkg-config File Generation Again Again
  .travis.yml
  Makefile
  build/cmake/lib/CMakeLists.txt
  lib/Makefile
  lib/libzstd.pc.in
Labels: CLA Signed, packaging issue, release-blocking

#2122 Compile Under `-Wunused-variable`
  programs/zstdcli.c
Labels: CLA Signed

#2120 updated zstd CLI documentation
  programs/README.md
Labels: CLA Signed

#2127 [doc] documenting non-supported grep options for zstdgrep to README
  programs/README.md
Labels: CLA Signed

#2128 Update benchmarks and add fast mode
  README.md
Labels: CLA Signed

#2129 Fix ZSTD_estimateCCtxSize() Under ASAN
  lib/compress/zstd_compress.c
Labels: CLA Signed, bug, test issue

#2123 updated `zstd -h`
  programs/Makefile
  programs/zstdcli.c
Labels: CLA Signed

#2124 re-inforced tests for initStaticCCtx
  tests/fuzzer.c
Labels: CLA Signed

#2117 [doc] measuring performance docs
  CONTRIBUTING.md
Labels: CLA Signed

#2130 Fix for initStatic
  lib/common/error_private.h
  lib/compress/zstd_compress.c
  lib/zstd.h
  tests/fuzzer.c
Labels: CLA Signed

#2125 programs/Makefile: make it actually work with clang
  programs/Makefile
Labels: CLA Signed

#2132 [build] removing -f test (grep usage not supported on mac)
  tests/playTests.sh
Labels: CLA Signed

#2134 [greedy] Fix performance instability
  lib/compress/zstd_lazy.c
Labels: CLA Signed

#2135 Revert to old zstdgrep because of potential license issue
  programs/README.md
  programs/zstdgrep
  tests/playTests.sh
Labels: CLA Signed

#2138 [lib] Fix bug in loading LDM dictionary in MT mode
  lib/compress/zstd_compress.c
  lib/compress/zstd_ldm.c
  tests/fuzzer.c
Labels: CLA Signed

#2141 [test][regression] Update results.csv
  tests/regression/results.csv
Labels: CLA Signed

#2140 [fuzz] Adding dictionary_stream_round_trip fuzzer
  tests/fuzz/Makefile
  tests/fuzz/dictionary_stream_round_trip.c
  tests/fuzz/fuzz.py
Labels: CLA Signed

#2146 Reduced single file lib size on macOS
  contrib/single_file_libs/README.md
  contrib/single_file_libs/combine.sh
  contrib/single_file_libs/create_single_file_library.sh
  contrib/single_file_libs/zstd-in.c
Labels: CLA Signed, Portability, build issue

#2148 Don't Use `[[` in Shell Scripts
  tests/playTests.sh
Labels: CLA Signed, Portability, test issue

#2150 [ldm] Reset loadedDictEnd when the context is reset
  lib/compress/zstd_compress.c
  lib/compress/zstd_ldm.c
  lib/compress/zstdmt_compress.c
  tests/fuzzer.c
Labels: CLA Signed, bug

#2151 fix 22294 & 22262
  lib/compress/zstd_fast.c
  lib/compress/zstd_ldm.c
  lib/compress/zstdmt_compress.c
  tests/fuzz/.gitignore
Labels: CLA Signed

#2152 [fuzz] Expand the allowedExpansion
  tests/fuzz/simple_round_trip.c
Labels: CLA Signed

#2153 [ldm][mt] Fix loadedDictEnd
  lib/compress/zstdmt_compress.c
  tests/fuzzer.c
Labels: CLA Signed

#2155 fixed zbuff test
  .travis.yml
  build/meson/tests/meson.build
Labels: CLA Signed

#2158 fix meson playTests.sh
  .travis.yml
  build/meson/tests/meson.build
  tests/playTests.sh
Labels: CLA Signed

#2159 Fix playTests.sh
  appveyor.yml
Labels: CLA Signed

#2163 Fix legacy build after #2103
  lib/legacy/zstd_v04.c
Labels: CLA Signed

#2166 do not install zbuff.h
  build/cmake/lib/CMakeLists.txt
  build/meson/lib/meson.build
  lib/Makefile
Labels: CLA Signed

#2167 [pzstd] Fix compilation error in MinGW
  contrib/pzstd/Logging.h
  contrib/pzstd/Pzstd.cpp
  contrib/pzstd/Pzstd.h
Labels: CLA Signed

#2177 updated spec on dictID==0
  doc/zstd_compression_format.md
Labels: CLA Signed

#2176 fixed default rule for lib/Makefile
  lib/Makefile
Labels: CLA Signed

#2178 Change --patch-from limit from 4gb to 2gb
  programs/fileio.c
Labels: CLA Signed

#2137 [actions] Migrating 1st batch of tests from Travis to Github Actions
  .github/workflows/generic-dev.yml
Labels: CLA Signed

#2180 [actions] Migrating 2nd batch of tests from Travis to Github Actions
  .github/workflows/generic-release.yml
Labels: CLA Signed

#2133 Consolidate CCtx Size Estimation Code
  lib/compress/zstd_compress.c
  lib/compress/zstd_cwksp.h
Labels: CLA Signed

#2181 fixed double-compilation of lib with make -j all
  Makefile
Labels: CLA Signed
