Repository facebook/zstd, pull requests merged in 2020-12, with the labels that each got.

#2405 Sequence Compression API - make validator use cctx minMatch instead of global MINMATCH
  lib/compress/zstd_compress.c
  lib/zstd.h
  tests/fuzz/sequence_compression_api.c
Labels: CLA Signed

#2348 Fix dll path in case of cross-compilation
  lib/Makefile
Labels: CLA Signed

#2407 [oss-fuzz] Move sequence compression API nbSequences check
  lib/compress/zstd_compress.c
Labels: CLA Signed

#2390 Clamp compression level
  lib/compress/zstd_compress.c
Labels: CLA Signed

#2409 Minor refactor
  doc/zstd_manual.html
  lib/zstd.h
  tests/Makefile
Labels: CLA Signed

#2406 [linux] Add the linux wrapper API
  contrib/linux-kernel/Makefile
  contrib/linux-kernel/decompress_sources.h
  contrib/linux-kernel/linux_zstd.h
  contrib/linux-kernel/test/Makefile
  contrib/linux-kernel/test/include/linux/module.h
  contrib/linux-kernel/test/static_test.c
  contrib/linux-kernel/test/test.c
  contrib/linux-kernel/zstd_compress_module.c
  contrib/linux-kernel/zstd_decompress_module.c
  lib/compress/zstd_compress.c
Labels: CLA Signed

#2410 [zlibWrapper] Only use public zstd functions
  zlibWrapper/zstd_zlibwrapper.c
Labels: CLA Signed

#2414 [lib] Ensure that multithreaded compression always makes some progress
  lib/compress/zstd_compress.c
  tests/zstreamtest.c
Labels: CLA Signed

#2412 use ZSTD_CLEVEL_DEFAULT in zdict.c
  lib/dictBuilder/zdict.c
Labels: CLA Signed

#2415 fix gcc-10 strict aliasing warnings
  lib/common/entropy_common.c
  lib/common/huf.h
  lib/compress/huf_compress.c
  lib/compress/zstd_compress_internal.h
  tests/decodecorpus.c
  zlibWrapper/zstd_zlibwrapper.c
Labels: CLA Signed

#2413 Paramgrill for windows
  build/cmake/tests/CMakeLists.txt
  tests/paramgrill.c
Labels: CLA Signed

#2417 [build] Fix icc build. Using updated ubuntu packages
  .github/workflows/generic-dev.yml
Labels: CLA Signed

#2408 Remove possibility of hanging when using seekable decompression
  Makefile
  contrib/seekable_format/tests/.gitignore
  contrib/seekable_format/tests/Makefile
  contrib/seekable_format/tests/seekable_tests.c
  contrib/seekable_format/zstdseek_decompress.c
Labels: CLA Signed

#2418 Fix various paramgrill conversion warnings
  tests/paramgrill.c
Labels: CLA Signed

#2419 Don't ASAN-Poison Statically-Allocated Workspaces
  lib/compress/zstd_compress.c
  lib/compress/zstd_cwksp.h
Labels: CLA Signed, bug

#2421 Don't Use Regexes to Build Pkg-Config File
  build/cmake/lib/CMakeLists.txt
  lib/Makefile
  lib/libzstd.pc.in
Labels: CLA Signed, build issue, packaging issue

#2422 Update Zstd Compression Format to Clarify Repcode Behavior
  doc/zstd_compression_format.md
Labels: CLA Signed, documentation

#2411 [cmake] Fix source directory with spaces
  .github/workflows/generic-dev.yml
  appveyor.yml
  build/cmake/lib/CMakeLists.txt
  build/cmake/tests/CMakeLists.txt
  tests/playTests.sh
Labels: CLA Signed

#2423 replace links by actual copies
  lib/Makefile
  programs/Makefile
Labels: CLA Signed

#2420 [huf_compress] Refactor and comment HUF_buildCTable()
  lib/compress/huf_compress.c
Labels: CLA Signed

#2425 add release dates to CHANGELOG
  CHANGELOG
Labels: CLA Signed

#2424 fix Integer Overflow
  programs/dibio.c
Labels: CLA Signed

#2427 streamlined example recipe
  Makefile
  examples/Makefile
Labels: CLA Signed

#2426 Updated CHANGELOG for v1.4.7
  CHANGELOG
  doc/zstd_manual.html
  lib/zstd.h
  programs/zstd.1
  programs/zstdgrep.1
  programs/zstdless.1
Labels: CLA Signed

#2429 Increase the hero text's line height for better readability
  index.html
Labels: CLA Signed

#2430 Fix alignment of scratchBuffer in HUF_compressWeights()
  lib/common/fse.h
  lib/compress/huf_compress.c
Labels: CLA Signed

#2432 added runtime test in CI for 32-bit binaries
  .circleci/config.yml
  .github/workflows/generic-dev.yml
  .github/workflows/generic-release.yml
  .github/workflows/linux-kernel.yml
  .travis.yml
  lib/common/fse.h
  lib/compress/huf_compress.c
  tests/playTests.sh
Labels: CLA Signed

#2433 Reduce workload on travisCI
  .github/workflows/generic-dev.yml
  .github/workflows/generic-release.yml
  .travis.yml
Labels: CLA Signed

#2434 added emphasis on the alignment condition of workspace
  lib/compress/huf_compress.c
Labels: CLA Signed

#2435 v1.4.8 hotfix
  .circleci/config.yml
  .github/workflows/generic-dev.yml
  .github/workflows/generic-release.yml
  .github/workflows/linux-kernel.yml
  .travis.yml
  CHANGELOG
  CONTRIBUTING.md
  README.md
  TESTING.md
  appveyor.yml
  contrib/seekable_format/zstd_seekable_compression_format.md
  doc/zstd_manual.html
  lib/common/fse.h
  lib/compress/huf_compress.c
  lib/compress/zstd_compress.c
  lib/decompress/zstd_decompress_block.c
  lib/zstd.h
  programs/zstd.1
  programs/zstdgrep.1
  programs/zstdless.1
  tests/README.md
  tests/automated_benchmarking.py
  tests/playTests.sh
Labels: CLA Signed

#2437 streamline zlibwrapper makefile
  .github/workflows/generic-release.yml
  zlibWrapper/Makefile
Labels: CLA Signed

#2440 try to fix 32-bit test on github actions
  .github/workflows/generic-dev.yml
Labels: CLA Signed

#2438 try to keep libzstd.a "as is" once created
  .circleci/config.yml
  .github/workflows/generic-dev.yml
  Makefile
  appveyor.yml
  lib/Makefile
  programs/Makefile
  tests/Makefile
Labels: CLA Signed

#2444 Add ifndef guards for _LARGEFILE_SOURCE and _LARGEFILE64_SOURCE
  lib/dictBuilder/zdict.c
Labels: CLA Signed

#2439 Generate skippable frame API
  lib/compress/zstd_compress.c
  lib/zstd.h
  tests/fuzzer.c
Labels: CLA Signed
