Repository facebook/zstd, pull requests merged in 2020-10, with the labels that each got.

#2333 Reset all decompression parameters in ZSTD_DCtx_reset()
  lib/decompress/zstd_decompress.c
  lib/zstd.h
  tests/fuzzer.c
Labels: CLA Signed

#2338 Add comments to ZSTD_getLowest{Match,Prefix}Index()
  lib/compress/zstd_compress_internal.h
Labels: CLA Signed

#2330 Improve error messages on console input/output
  programs/zstdcli.c
Labels: CLA Signed

#2319 update fullbench for compressStream2()
  tests/fullbench.c
Labels: CLA Signed

#2303 For ZSTD_compressStream2(), let cdict take compression level priority
  lib/compress/zstd_compress.c
Labels: CLA Signed

#2328 Allow external creation of POOLs that can be shared.
  examples/streaming_compression_thread_pool.c
  lib/common/pool.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstdmt_compress.c
  lib/compress/zstdmt_compress.h
  lib/zstd.h
Labels: CLA Signed

#2329 Prevent summary updates when using stdout
  programs/fileio.c
  programs/fileio.h
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2337 Fix ZSTD_adjustCParams_internal() to handle dictionary logic
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstdmt_compress.c
  tests/fuzzer.c
Labels: CLA Signed

#2341 Integrate long distance matches into optimal parser
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_ldm.c
  lib/compress/zstd_opt.c
  lib/compress/zstdmt_compress.c
  tests/fuzzer.c
  tests/playTests.sh
Labels: CLA Signed

#2281 Fix building on AIX 5.1
  lib/common/mem.h
  lib/legacy/zstd_v01.c
  lib/legacy/zstd_v02.c
  lib/legacy/zstd_v03.c
  lib/legacy/zstd_v04.c
  lib/legacy/zstd_v05.c
  lib/legacy/zstd_v06.c
  lib/legacy/zstd_v07.c
  programs/timefn.h
Labels: CLA Signed

#2356 aarch64: use __ARM_NEON instead of __aarch64__ to control use of neon
  lib/common/zstd_internal.h
Labels: CLA Signed

#2360 fix zwrapbench parallel build
  zlibWrapper/Makefile
Labels: CLA Signed

#2361 [travis CI] Change make -j all check to make -j all && make check
  .travis.yml
Labels: CLA Signed

#2357 Fix nondeterministic LDM behavior in multithreading
  lib/compress/zstd_ldm.c
Labels: CLA Signed

#2355 Reduce --long mode MT jobsize at higher levels
  lib/compress/zstdmt_compress.c
  programs/fileio.c
Labels: CLA Signed

#2359 [minor] Fix some /tests/fuzz Makefile annoyances
  tests/fuzz/.gitignore
  tests/fuzz/Makefile
Labels: CLA Signed

#2365 Move ldm + opt parser no regression test to long tests
  tests/fuzzer.c
Labels: CLA Signed

#2367 faster rebuild of zstd
  .travis.yml
  appveyor.yml
  lib/dictBuilder/zdict.h
  programs/Makefile
Labels: CLA Signed

#2368 faster rebuild of libzstd
  lib/Makefile
Labels: CLA Signed

#2370 Automatic configuration detection
  Makefile
  appveyor.yml
  lib/Makefile
  lib/README.md
  programs/Makefile
  programs/README.md
  tests/Makefile
  tests/libzstd_partial_builds.sh
Labels: CLA Signed

#2372 Add TrueNAS to OS's supporting ZSTD
  images/truenas.png
  index.html
Labels: Announce, CLA Signed

#2362 Fix long distance matcher OSS-fuzz issue
  lib/compress/zstd_compress.c
  lib/compress/zstd_ldm.c
  lib/compress/zstd_ldm.h
Labels: CLA Signed

#2366 Enable LDM by default if window size >= 128MB and strategy uses opt parser
  lib/compress/zstd_compress.c
  lib/zstd.h
  tests/fuzzer.c
Labels: CLA Signed

#2374 'head -c BYTES' is non-portable
  lib/Makefile
  programs/Makefile
Labels: CLA Signed, Portability

#2339 Fix zstdmt stability issues and clean up the zstdmt code
  lib/compress/zstdmt_compress.c
  lib/compress/zstdmt_compress.h
  tests/Makefile
  tests/fuzzer.c
  tests/zstreamtest.c
Labels: CLA Signed

#2373 Automatic detection of configuration changes
  lib/Makefile
  programs/Makefile
Labels: CLA Signed

#2375 Add a test case for LDM + opt parser with small uncompressible block
  tests/fuzzer.c
Labels: CLA Signed

#2376 Refine external ZSTD_Sequence API
  lib/common/zstd_internal.h
  lib/compress/zstd_compress.c
  lib/zstd.h
  tests/fuzzer.c
Labels: CLA Signed

#2354 Add ZSTD_c_stable{In,Out}Buffer and optimize when set
  lib/common/error_private.c
  lib/common/zstd_errors.h
  lib/common/zstd_internal.h
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_cwksp.h
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_internal.h
  lib/zstd.h
  tests/zstreamtest.c
Labels: CLA Signed

#2379 [regression] Updates results.csv & add README
  tests/regression/README.md
  tests/regression/results.csv
Labels: CLA Signed
