Repository facebook/zstd, pull requests merged in 2020-08, with the labels that each got.

#2253 optimized histogram
  lib/compress/hist.c
Labels: CLA Signed

#2258 Added STATIC_BMI2 for compile time detection of BMI2 on MSVC, when enabled various intrinsics are used
  lib/common/bitstream.h
  lib/common/compiler.h
  lib/common/zstd_internal.h
  lib/compress/zstd_compress_internal.h
Labels: CLA Signed, optimization

#2262 Share stat() Calls Where Convenient
  programs/fileio.c
  programs/util.c
  programs/util.h
Labels: CLA Signed, optimization, refactor

#2265 Prefer __builtin_prefetch over inline asm
  lib/common/compiler.h
Labels: CLA Signed

#2267 Fix clang -Wcomma warning (single file decoder)
  lib/decompress/zstd_decompress_block.c
Labels: CLA Signed

#2270 Fix Documentation for ZSTD_CCtxParams_setParameter()
  lib/zstd.h
Labels: CLA Signed, documentation

#2268 [actions] removing broken icc test from travis and adding working version to actions
  .github/workflows/generic-dev.yml
  .travis.yml
Labels: CLA Signed

#2277 Fixed Markdown warnings. No visible changes.
  lib/dll/example/README.md
Labels: CLA Signed

#2271 Small block optimizations
  lib/common/entropy_common.c
  lib/common/fse.h
  lib/common/fse_decompress.c
  lib/common/huf.h
  lib/compress/fse_compress.c
  lib/compress/huf_compress.c
  lib/compress/zstd_compress_sequences.c
  lib/decompress/huf_decompress.c
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_block.c
  lib/decompress/zstd_decompress_block.h
  lib/decompress/zstd_decompress_internal.h
  lib/dictBuilder/zdict.c
  tests/decodecorpus.c
  tests/fullbench.c
  tests/fuzzer.c
  tests/regression/results.csv
Labels: CLA Signed

#2280 Add a Couple Use Cases to the Zstd Web-Page
  images/apache-arrow.png
  images/curl.png
  index.html
Labels: Announce, CLA Signed, documentation

#2278 New advanced decompression param to ignore checksums
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_internal.h
  lib/zstd.h
  programs/fileio.c
  programs/zstdcli.c
  tests/fuzzer.c
  tests/playTests.sh
Labels: CLA Signed, feature

#2284 [github actions] Disable armbuild and armfuzz tests
  .github/workflows/generic-dev.yml
Labels: CLA Signed

#2285 [fuzz] Fix oss-fuzz test problems
  tests/fuzz/fuzz_data_producer.c
  tests/fuzz/fuzz_data_producer.h
  tests/fuzz/simple_round_trip.c
  tests/fuzz/stream_decompress.c
Labels: CLA Signed

#2282 [bug] Fix FSE_readNCount()
  lib/common/entropy_common.c
  tests/fuzz/Makefile
  tests/fuzz/fse_read_ncount.c
  tests/fuzz/fuzz.py
Labels: CLA Signed

#2283 Refreshing progress bar for processing multiple files
  programs/fileio.c
  programs/fileio.h
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2264 Prepare for freestanding library and add initial translator script
  contrib/freestanding_lib/freestanding.py
  contrib/freestanding_lib/test/Makefile
  contrib/freestanding_lib/test/test.c
  contrib/freestanding_lib/test/zstd_deps.h
  contrib/single_file_libs/zstd-in.c
  contrib/single_file_libs/zstddeclib-in.c
  lib/common/bitstream.h
  lib/common/cpu.h
  lib/common/debug.h
  lib/common/entropy_common.c
  lib/common/error_private.h
  lib/common/fse.h
  lib/common/fse_decompress.c
  lib/common/huf.h
  lib/common/mem.h
  lib/common/pool.c
  lib/common/pool.h
  lib/common/threading.c
  lib/common/xxhash.c
  lib/common/xxhash.h
  lib/common/zstd_common.c
  lib/common/zstd_deps.h
  lib/common/zstd_internal.h
  lib/compress/fse_compress.c
  lib/compress/hist.c
  lib/compress/hist.h
  lib/compress/huf_compress.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_compress_literals.c
  lib/compress/zstd_compress_sequences.c
  lib/compress/zstd_compress_superblock.c
  lib/compress/zstd_cwksp.h
  lib/compress/zstd_opt.c
  lib/compress/zstdmt_compress.c
  lib/compress/zstdmt_compress.h
  lib/decompress/huf_decompress.c
  lib/decompress/zstd_ddict.c
  lib/decompress/zstd_ddict.h
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_block.c
  lib/decompress/zstd_decompress_block.h
  zlibWrapper/zstd_zlibwrapper.c
Labels: CLA Signed

#2288 [doc] Add ZSTD_versionString() to manual
  lib/zstd.h
Labels: CLA Signed
