Repository facebook/zstd, pull requests merged in 2020-09, with the labels that each got.

#2279 Add a warning whenever (de)compressing multiple files
  programs/fileio.c
  programs/util.c
  programs/util.h
  programs/zstd.1.md
  tests/playTests.sh
Labels: CLA Signed

#2293 Resolve Coverity 1432392 Unintentional integer overflow
  lib/compress/zstd_compress.c
Labels: CLA Signed

#2294 Fix Makefile Variable Concatenation Order
  lib/Makefile
Labels: CLA Signed, build issue

#2291 Fix setParameter not falling back to default compression level
  lib/compress/zstd_compress.c
Labels: CLA Signed

#2301 Prepare library for a release
  CHANGELOG
  lib/README.md
  lib/zstd.h
Labels: CLA Signed

#2276 DDSS For Lazy: Implement a Dedicated Dictionary Hash Table
  contrib/largeNbDicts/largeNbDicts.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_lazy.c
  lib/compress/zstd_lazy.h
  lib/zstd.h
  programs/fileio.c
  tests/fuzzer.c
Labels: CLA Signed, optimization

#2295 DDSS for Lazy: Implement a Dedicated Dictionary Chain Table
  lib/compress/zstd_compress.c
  lib/compress/zstd_lazy.c
  lib/zstd.h
  tests/fuzzer.c
Labels: CLA Signed, optimization

#2306 check endDirective in ZSTD_compressStream2()
  lib/compress/zstd_compress.c
  lib/zstd.h
  tests/fuzzer.c
Labels: CLA Signed

#2299 Allow environment variable to specify number of threads for compression
  programs/README.md
  programs/zstd.1.md
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2292 Make multifile (de)compression print out a summary
  programs/fileio.c
  programs/fileio.h
  programs/zstdcli.c
Labels: CLA Signed

#2308 [contrib][linux-kernel] Add decompress_sources.h
  contrib/linux-kernel/Makefile
  contrib/linux-kernel/decompress_sources.h
  contrib/linux-kernel/test/Makefile
  contrib/linux-kernel/test/static_test.c
Labels: CLA Signed

#2313 Separate Long Tests in Fuzzer
  .github/workflows/generic-dev.yml
  tests/fuzzer.c
Labels: CLA Signed

#2311 Fix Compression Parameter Derivation Bugs Introduced by DDSS Changes
  lib/compress/zstd_compress.c
  lib/zstd.h
  tests/regression/results.csv
Labels: CLA Signed, bug

#2320 [tests] Don't write to stdout
  tests/playTests.sh
Labels: CLA Signed

#2324 Silence warnings reported by Kernel Test Robot
  .github/workflows/linux-kernel.yml
  contrib/linux-kernel/Makefile
  contrib/linux-kernel/zstd_deps.h
  lib/common/zstd_internal.h
  lib/decompress/zstd_decompress_internal.h
  lib/zstd.h
Labels: CLA Signed

#2315 Support .zstd suffix only for decompression
  .gitignore
  programs/fileio.c
  programs/fileio.h
  tests/playTests.sh
Labels: CLA Signed

#2310 Fix multifile status bar and summary - clear out extraneous characters
  programs/fileio.c
Labels: CLA Signed

#2326 Fix issues and warnings exposed by Kernel Test Robot
  contrib/freestanding_lib/freestanding.py
  contrib/linux-kernel/Makefile
  contrib/linux-kernel/mem.h
  contrib/linux-kernel/test/include/asm/unaligned.h
  contrib/linux-kernel/test/include/linux/compiler.h
  contrib/linux-kernel/test/include/linux/swab.h
  contrib/linux-kernel/test/include/linux/xxhash.h
  contrib/linux-kernel/zstd_deps.h
  lib/common/bitstream.h
  lib/common/compiler.h
  lib/common/mem.h
  lib/common/xxhash.c
  lib/common/zstd_deps.h
  lib/common/zstd_internal.h
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_superblock.c
  lib/compress/zstd_cwksp.h
  lib/decompress/zstd_ddict.c
  lib/decompress/zstd_decompress.c
  zlibWrapper/zstd_zlibwrapper.c
Labels: CLA Signed

#2322 Don't let warning messages consume input from stdin
  programs/fileio.c
  programs/fileio.h
  programs/util.c
  programs/util.h
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2321 Update documentation about repcodes in dictionaries
  doc/zstd_compression_format.md
Labels: CLA Signed

#2317 Let MSVC force inline ZSTD_hashPtr() function
  lib/compress/zstd_compress_internal.h
Labels: CLA Signed
