Repository facebook/zstd, pull requests merged in 2021-06, with the labels that each got.

#2684 Add ldm and block splitter auto-enable to old api
  lib/compress/zstd_compress.c
  tests/regression/Makefile
  tests/regression/results.csv
Labels: CLA Signed

#2693 Add documentation for --patch-from
  programs/README.md
  programs/zstdcli.c
Labels: CLA Signed

#2691 Make regression test run on every PR
  .circleci/config.yml
Labels: CLA Signed

#2654 Initialize "potentially uninitialized" pointers.
  lib/compress/zstd_lazy.c
Labels: CLA Signed

#2696 Make the CLI summary data use a human readable format instead of raw bytes
  programs/benchzstd.c
  programs/fileio.c
  programs/util.c
  programs/util.h
Labels: CLA Signed, enhancement

#2681 Flatten ZSTD_row_getMatchMask
  lib/common/compiler.h
  lib/common/mem.h
  lib/common/zstd_internal.h
  lib/compress/zstd_compress.c
  lib/compress/zstd_lazy.c
Labels: CLA Signed

#2700 Update README for Travis CI Badge
  README.md
Labels: CLA Signed

#2678 Fuzzer test with no intrinsics on S390x (big endian)
  .github/workflows/dev-long-tests.yml
  .travis.yml
  tests/fuzzer.c
Labels: CLA Signed

#2698 Fix --progress flag to properly control progress display and default …
  programs/fileio.c
  tests/playTests.sh
Labels: CLA Signed

#2703 Add support for --long-param flag, fix #2104
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2704 Revert "Add support for --long-param flag, fix #2104"
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2697 [bug] Fix entropy repeat mode bug
  lib/compress/zstd_compress.c
Labels: CLA Signed

#2702 Format File Sizes Human-Readable in the CLI
  programs/benchzstd.c
  programs/fileio.c
  programs/util.c
  programs/util.h
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2705 Add support for negative values in advanced flags
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2683 Added C# port link
  index.html
Labels: Announce, CLA Signed

#2709 [fix] Add missing bounds checks during compression
  lib/compress/huf_compress.c
  lib/compress/zstd_compress.c
Labels: CLA Signed

#2708 Add API for fetching skippable frame content
  lib/decompress/zstd_decompress.c
  lib/zstd.h
  tests/fuzzer.c
Labels: CLA Signed

#2710 Add option to use logical cores for default threads
  programs/util.c
  programs/util.h
  programs/zstd.1.md
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2714 lib/Makefile: Fix small typo in ZSTD_FORCE_DECOMPRESS_* build macros
  lib/Makefile
Labels: CLA Signed

#2715 [RFC] Add internal API for converting ZSTD_Sequence into seqStore
  lib/compress/zstd_compress.c
Labels: CLA Signed

#2716 remove invalid test
  build/meson/tests/meson.build
Labels: CLA Signed

#2689 Optimize zstd decompression by another x%
  lib/common/bitstream.h
  lib/decompress/zstd_decompress_block.c
Labels: CLA Signed

#2719 Include what you use in zstd_ldm_geartab
  lib/compress/zstd_ldm_geartab.h
Labels: CLA Signed

#2655 [trace] remove zstd_trace.c reference from freestanding
  contrib/freestanding_lib/freestanding.py
Labels: CLA Signed

#2720 Remove folder when done with test
  tests/playTests.sh
Labels: CLA Signed
