Repository facebook/zstd, pull requests merged in 2021-12, with the labels that each got.

#2877 Add detection when compiling with Clang and Ninja under Windows
  build/cmake/lib/CMakeLists.txt
Labels: CLA Signed

#2889 [contrib][pzstd] Fix build issue with gcc-5
  contrib/pzstd/utils/Buffer.h
  contrib/pzstd/utils/Range.h
Labels: CLA Signed

#2888 [bmi2] Add lzcnt and bmi target attributes
  lib/common/compiler.h
  lib/common/entropy_common.c
  lib/common/fse_decompress.c
  lib/common/zstd_internal.h
  lib/compress/huf_compress.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_sequences.c
  lib/decompress/huf_decompress.c
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_block.c
Labels: CLA Signed

#2886 [test] Test that the exec-stack bit isn't set on libzstd.so
  .github/workflows/dev-short-tests.yml
  tests/libzstd_builds.sh
Labels: CLA Signed

#2885 Limit `ZSTD_maxCLevel` to 21 for 32-bit binaries.
  .github/workflows/dev-short-tests.yml
  doc/zstd_manual.html
  lib/compress/clevels.h
  lib/compress/zstd_compress.c
  tests/fuzzer.c
  tests/playTests.sh
Labels: CLA Signed

#2876 Solve the bug of extra output newline character
  programs/fileio.c
  tests/playTests.sh
Labels: CLA Signed

#2887 [zdict] Remove ZDICT_CONTENTSIZE_MIN restriction for ZDICT_finalizeDictionary
  lib/dictBuilder/zdict.c
  lib/zdict.h
  tests/playTests.sh
Labels: CLA Signed

#2501 Explicitly hide static symbols
  lib/Makefile
  lib/compress/zstd_compress.c
  lib/zstd.h
Labels: CLA Signed

#2895 Makefile: sort all wildcard file list expansions
  programs/Makefile
  tests/Makefile
  tests/fuzz/Makefile
Labels: CLA Signed, build issue

#2894 merge #2501
  lib/Makefile
  lib/compress/zstd_compress.c
  lib/zstd.h
Labels: CLA Signed

#2687 Makefile: fix build for mingw
  programs/Makefile
Labels: CLA Signed

#2891 Fix typos
  lib/compress/zstd_compress.c
Labels: CLA Signed

#2892 [CircleCI] Fix short-tests-0
  .circleci/config.yml
  .github/workflows/dev-long-tests.yml
  examples/common.h
  lib/common/compiler.h
  lib/compress/zstd_lazy.c
  lib/decompress/huf_decompress_amd64.S
  tests/zstreamtest.c
Labels: CLA Signed

#2896 Zstandard compiles and run on m68k cpus
  .github/workflows/dev-short-tests.yml
  lib/common/compiler.h
  lib/compress/huf_compress.c
  lib/compress/zstd_cwksp.h
Labels: CLA Signed

#2898 Improve zstd_opt build speed and size
  lib/compress/zstd_opt.c
Labels: CLA Signed

#2900 [CI] Add cmake windows build
  .github/workflows/dev-short-tests.yml
Labels: CLA Signed

#2899 Disable Multithreading in CMake Builds for Android
  build/cmake/CMakeLists.txt
Labels: CLA Signed, build issue

#2897 Avoid Using Deprecated Functions in Deprecated Code
  lib/deprecated/zbuff_compress.c
Labels: CLA Signed

#2893 [asm] Share portability macros and restrict ASM further
  build/single_file_libs/zstd-in.c
  build/single_file_libs/zstddeclib-in.c
  contrib/linux-kernel/decompress_sources.h
  lib/common/compiler.h
  lib/common/portability_macros.h
  lib/decompress/huf_decompress.c
  lib/decompress/huf_decompress_amd64.S
  lib/libzstd.mk
Labels: CLA Signed

#2890 fixbug CLI's -D fails when the argument is not a regular file
  programs/fileio.c
Labels: CLA Signed

#2907 Apply FORCE_MEMORY_ACCESS=1 to legacy
  lib/legacy/zstd_v01.c
  lib/legacy/zstd_v02.c
  lib/legacy/zstd_v03.c
  lib/legacy/zstd_v04.c
  lib/legacy/zstd_v05.c
  lib/legacy/zstd_v06.c
  lib/legacy/zstd_v07.c
Labels: CLA Signed

#2659 [lib] Fix libzstd.pc for lib-mt builds
  lib/Makefile
  lib/libzstd.pc.in
Labels: CLA Signed, release-blocking

#2884 Imply -q when stderr is not a tty
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2915 Fix oss-fuzz build
  lib/common/portability_macros.h
Labels: CLA Signed

#2916 Remove possible NULL pointer addition
  lib/compress/zstdmt_compress.c
Labels: CLA Signed

#2914 updated xxHash to latest v0.8.1
  lib/common/xxhash.c
  lib/common/xxhash.h
  tests/fuzzer.c
Labels: CLA Signed

#2910 Reject Irregular Dictionary Files
  programs/fileio.c
  tests/playTests.sh
Labels: CLA Signed

#2917 Update changelog for v1.5.1
  CHANGELOG
Labels: CLA Signed

#2922 x32 compatibility
  .github/workflows/dev-short-tests.yml
  lib/decompress/huf_decompress.c
Labels: CLA Signed

#2923 typo: Small spelling mistake in example
  examples/streaming_compression.c
Labels: CLA Signed

#2905 add test case
  tests/playTests.sh
Labels: CLA Signed

#2921 Stagger Stepping in Negative Levels
  lib/compress/zstd_fast.c
  tests/fuzzer.c
  tests/regression/results.csv
Labels: CLA Signed

#2926 Fix performance degradation with -m32
  lib/common/zstd_internal.h
Labels: CLA Signed

#2930 Reduce tables to 8bit
  contrib/linux-kernel/mem.h
  lib/common/mem.h
  lib/common/zstd_internal.h
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_superblock.c
  lib/decompress/zstd_decompress_block.c
  lib/decompress/zstd_decompress_block.h
  lib/decompress/zstd_decompress_internal.h
Labels: CLA Signed

#2929 simplify SSE implementation of row_lazy match finder
  lib/compress/zstd_lazy.c
Labels: CLA Signed

#2925 Allow user to specify memory limit for dictionary training
  programs/dibio.c
  programs/dibio.h
  programs/zstd.1.md
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2931 fixed incorrect rowlog initialization
  lib/compress/zstd_lazy.c
Labels: CLA Signed

#2936 Add Kiwix to software list
  images/kiwix.png
  index.html
Labels: CLA Signed

#2934 rebalance lazy compression levels
  lib/compress/clevels.h
  tests/regression/results.csv
Labels: CLA Signed

#2940 Revert "Limit `ZSTD_maxCLevel` to 21 for 32-bit binaries."
  .github/workflows/dev-short-tests.yml
  doc/zstd_manual.html
  lib/compress/clevels.h
  lib/compress/zstd_compress.c
  tests/fuzzer.c
  tests/playTests.sh
Labels: CLA Signed

#2942 update man pages for v1.5.1
  programs/zstd.1
  programs/zstdgrep.1
  programs/zstdless.1
Labels: CLA Signed

#2947 Fix zstd-static output name with MINGW/Clang
  build/cmake/lib/CMakeLists.txt
Labels: CLA Signed

#2954 storeSeq & mlBase : clarity refactoring
  lib/common/zstd_internal.h
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_compress_sequences.c
  lib/compress/zstd_double_fast.c
  lib/compress/zstd_fast.c
  lib/compress/zstd_lazy.c
  lib/compress/zstd_ldm.c
  lib/compress/zstd_opt.c
  tests/decodecorpus.c
Labels: CLA Signed

#2960 Fix mini typo
  examples/streaming_compression_thread_pool.c
Labels: CLA Signed
