Repository facebook/zstd, pull requests merged in 2021-09, with the labels that each got.

#2763 Improve compile speed and binary size in `opt`
  lib/compress/zstd_opt.c
Labels: CLA Signed

#2769 [easy] Fix patch-from help msg typo
  programs/fileio.c
Labels: CLA Signed

#2749 Pipelined Implementation of ZSTD_fast (~+5% Speed)
  lib/compress/zstd_fast.c
  programs/benchzstd.c
  tests/fuzzer.c
  tests/regression/results.csv
Labels: CLA Signed, optimization

#2775 meson: fix type error for integer option
  build/meson/meson_options.txt
Labels: CLA Signed

#2773 Fix dictionary training huffman segfault and small speed improvement
  lib/compress/huf_compress.c
  tests/playTests.sh
  tests/regression/results.csv
Labels: CLA Signed

#2776 [rsyncable] Ensure ZSTD_compressBound() is respected
  lib/compress/zstdmt_compress.c
Labels: CLA Signed

#2771 Improve optimal parser performance on small data
  lib/compress/zstd_opt.c
  lib/dictBuilder/cover.c
  lib/dictBuilder/fastcover.c
  lib/dictBuilder/zdict.c
  programs/benchzstd.c
  programs/util.c
  programs/util.h
  tests/automated_benchmarking.py
  tests/fuzzer.c
  tests/regression/results.csv
Labels: CLA Signed

#2777 [rsyncable] Fix test failures
  lib/compress/zstdmt_compress.c
Labels: CLA Signed

#2778 Revert opt outlining change
  lib/compress/zstd_opt.c
Labels: CLA Signed

#2783 [build] Add support for ASM files in Make + CMake
  .circleci/config.yml
  .github/workflows/dev-short-tests.yml
  Makefile
  build/cmake/lib/CMakeLists.txt
  contrib/freestanding_lib/freestanding.py
  contrib/linux-kernel/test/Makefile
  contrib/pzstd/Makefile
  lib/Makefile
  lib/compress/huf_compress.c
  lib/libzstd.mk
  programs/Makefile
  tests/Makefile
  tests/fuzz/Makefile
  tests/fuzzer.c
  tests/regression/Makefile
  tests/test-variants.sh
Labels: CLA Signed

#2787 add msvc2019 to build.generic.cmd
  build/VS_scripts/build.generic.cmd
Labels: CLA Signed

#2784 [fuzzer] Add Huffman decompression fuzzer
  lib/decompress/huf_decompress.c
  tests/fuzz/Makefile
  tests/fuzz/fuzz.py
  tests/fuzz/huf_decompress.c
Labels: CLA Signed

#2722 Assembly implementation of 4X1 & 4X2 Huffman
  build/meson/lib/meson.build
  build/single_file_libs/zstd-in.c
  build/single_file_libs/zstddeclib-in.c
  contrib/linux-kernel/Makefile
  contrib/linux-kernel/decompress_sources.h
  contrib/linux-kernel/test/macro-test.sh
  lib/common/compiler.h
  lib/common/error_private.h
  lib/common/huf.h
  lib/common/zstd_internal.h
  lib/compress/huf_compress.c
  lib/decompress/huf_decompress.c
  lib/decompress/huf_decompress_amd64.S
  lib/zstd.h
  tests/fuzz/huf_decompress.c
Labels: CLA Signed, optimization

#2791 [huf] Fix compilation when DYNAMIC_BMI2=0 && BMI2 is supported
  .github/workflows/dev-short-tests.yml
  lib/decompress/huf_decompress.c
Labels: CLA Signed

#2788 Use new paramSwitch enum for row matchfinder and block splitter
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_ldm.c
  lib/compress/zstd_ldm.h
  lib/compress/zstd_opt.c
  lib/compress/zstdmt_compress.c
  lib/zstd.h
  programs/benchzstd.c
  programs/benchzstd.h
  programs/fileio.c
  programs/fileio.h
  programs/zstdcli.c
  tests/fuzz/zstd_helpers.c
  tests/fuzzer.c
  tests/regression/config.c
  tests/regression/levels.h
  tests/regression/results.csv
Labels: CLA Signed

#2779 Fix NCountWriteBound
  lib/compress/fse_compress.c
  tests/fuzzer.c
Labels: CLA Signed

#2793 Minor documentation update
  programs/zstd.1
  programs/zstd.1.md
  programs/zstdgrep.1
  programs/zstdgrep.1.md
  programs/zstdless.1
Labels: CLA Signed

#2794 [contrib][linux] Fix up SPDX license identifiers
  contrib/linux-kernel/decompress_sources.h
  contrib/linux-kernel/linux.mk
  contrib/linux-kernel/linux_zstd.h
  contrib/linux-kernel/mem.h
  contrib/linux-kernel/zstd_compress_module.c
  contrib/linux-kernel/zstd_decompress_module.c
  contrib/linux-kernel/zstd_deps.h
Labels: CLA Signed

#2795 [contrib][linux] Reduce stack usage by 80 bytes
  contrib/linux-kernel/zstd_compress_module.c
Labels: CLA Signed

#2780 Reduce stack usage of block splitter
  contrib/linux-kernel/Makefile
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
Labels: CLA Signed

#2797 minor: constify MatchState* parameter when possible
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_lazy.c
  lib/compress/zstd_opt.c
Labels: CLA Signed

#2798 Fix typo
  lib/zstd.h
Labels: CLA Signed

#2799 [build] Fix oss-fuzz build with the dataflow sanitizer
  lib/common/compiler.h
  lib/decompress/huf_decompress.c
Labels: CLA Signed

#2796 [lib] Make lib compatible with `-Wfall-through` excepting legacy
  .github/workflows/dev-short-tests.yml
  contrib/linux-kernel/Makefile
  contrib/linux-kernel/test/include/linux/compiler.h
  lib/common/bitstream.h
  lib/common/compiler.h
  lib/compress/huf_compress.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_double_fast.c
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_block.c
Labels: CLA Signed

#2790 [contrib][linux] Fix build after introducing ASM HUF implementation
  .gitignore
  contrib/linux-kernel/linux.mk
Labels: CLA Signed

#2805 Smaller code with disabled features
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_block.c
  lib/decompress/zstd_decompress_internal.h
  tests/fullbench.c
Labels: CLA Signed

#2808 [huf] Fix OSS-Fuzz assert
  lib/decompress/huf_decompress.c
Labels: CLA Signed

#2755 Skip most long matches in lazy hash table update
  lib/compress/zstd_lazy.c
  tests/regression/results.csv
Labels: CLA Signed

#2810 add missing BUNDLE DESTINATION
  build/cmake/lib/CMakeLists.txt
  build/cmake/programs/CMakeLists.txt
Labels: CLA Signed, build issue

#2802 [contrib][linux] Fix -Wundef inside Linux kernel tree
  lib/decompress/huf_decompress.c
Labels: CLA Signed
