Repository facebook/zstd, pull requests merged in 2022-01, with the labels that each got.

#2951 meson: fix MSVC support
  build/meson/lib/meson.build
Labels: CLA Signed

#2969 fix performance issue in scenario #2966 (part 1)
  lib/compress/zstd_cwksp.h
Labels: CLA Signed, Performance

#2972 [meson] Explicitly disable assembly for non clang/gcc copmilers
  build/meson/lib/meson.build
Labels: CLA Signed

#2964 Mark Huffman Decoder Assembly `noexecstack` on All Architectures
  lib/decompress/huf_decompress_amd64.S
  lib/libzstd.mk
  programs/Makefile
  tests/playTests.sh
Labels: CLA Signed, build issue, release-blocking

#2953 Improve Module Map File
  Package.swift
  lib/module.modulemap
  lib/modulemap/module.modulemap
Labels: enhancement, CLA Signed, build issue

#2977 Remove Dependencies to Allow the Zstd Binary to Dynamically Link to the Library
  programs/benchzstd.c
  programs/dibio.c
Labels: CLA Signed

#2980 [opt] Fix oss-fuzz bug in optimal parser
  lib/compress/zstd_opt.c
Labels: CLA Signed

#2981 [license] Fix license header of huf_decompress_amd64.S
  lib/decompress/huf_decompress_amd64.S
  tests/test-license.py
Labels: CLA Signed

#2982 Fix stderr progress logging for decompression
  programs/fileio.c
Labels: CLA Signed, release-blocking

#2956 Fix tar test cases
  tests/playTests.sh
Labels: CLA Signed, release-blocking

#2957 Fixup MSVC source file inclusion for cmake builds
  build/cmake/lib/CMakeLists.txt
Labels: CLA Signed, release-blocking

#2993 x86-64: Hide internal assembly functions
  lib/common/portability_macros.h
  lib/decompress/huf_decompress.c
  lib/decompress/huf_decompress_amd64.S
Labels: CLA Signed

#2987 Prepare v1.5.2
  CHANGELOG
  doc/zstd_manual.html
  lib/zstd.h
  programs/zstd.1
  programs/zstdgrep.1
  programs/zstdless.1
Labels: CLA Signed

#3000 Documentation and minor refactor to clarify MT memory management
  lib/compress/zstdmt_compress.c
  lib/compress/zstdmt_compress.h
Labels: CLA Signed

#2998 Avoid updating timestamps when the destination is stdout
  programs/fileio.c
Labels: CLA Signed

#3009 [build][asm] Pass ASFLAGS to the assembler instead of CFLAGS
  contrib/linux-kernel/test/Makefile
  lib/Makefile
  lib/libzstd.mk
  programs/Makefile
  tests/Makefile
  tests/fuzz/Makefile
Labels: CLA Signed

#2992 x86-64: Enable Intel CET
  lib/common/portability_macros.h
Labels: CLA Signed

#2994 x86: Append -z cet-report=error to LDFLAGS
  lib/libzstd.mk
Labels: CLA Signed, test issue

#3016 Minor lint fix
  lib/compress/zstdmt_compress.c
Labels: CLA Signed

#2995 Zstandard v1.5.2
  CHANGELOG
  CONTRIBUTING.md
  Package.swift
  build/cmake/lib/CMakeLists.txt
  build/meson/lib/meson.build
  contrib/linux-kernel/test/Makefile
  doc/zstd_manual.html
  examples/streaming_compression_thread_pool.c
  lib/Makefile
  lib/common/pool.c
  lib/common/pool.h
  lib/common/portability_macros.h
  lib/common/zstd_internal.h
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_compress_sequences.c
  lib/compress/zstd_compress_superblock.c
  lib/compress/zstd_cwksp.h
  lib/compress/zstd_double_fast.c
  lib/compress/zstd_fast.c
  lib/compress/zstd_lazy.c
  lib/compress/zstd_ldm.c
  lib/compress/zstd_opt.c
  lib/compress/zstdmt_compress.c
  lib/compress/zstdmt_compress.h
  lib/decompress/huf_decompress.c
  lib/decompress/huf_decompress_amd64.S
  lib/dictBuilder/zdict.c
  lib/libzstd.mk
  lib/module.modulemap
  lib/modulemap/module.modulemap
  lib/zstd.h
  programs/Makefile
  programs/benchzstd.c
  programs/dibio.c
  programs/fileio.c
  programs/zstd.1
  programs/zstdgrep.1
  programs/zstdless.1
  tests/Makefile
  tests/decodecorpus.c
  tests/fullbench.c
  tests/fuzz/.gitignore
  tests/fuzz/Makefile
  tests/fuzz/sequence_compression_api.c
  tests/fuzz/zstd_helpers.c
  tests/playTests.sh
  tests/test-license.py
Labels: CLA Signed

#3015 Add GitHub Action Checking that Zstd Runs Successfully Under CET
  .github/workflows/dev-short-tests.yml
Labels: CLA Signed

#2983 [opt] minor compression ratio improvement
  lib/compress/zstd_opt.c
  tests/regression/results.csv
Labels: CLA Signed

#3018 Trigger Release Artifact Generation on Publish
  .github/workflows/publish-release-artifacts.yml
Labels: CLA Signed

#3013 Simplify HUF_decompress4X2_usingDTable_internal_bmi2_asm_loop
  lib/decompress/huf_decompress_amd64.S
Labels: CLA Signed

#2975 Async write for decompression
  build/meson/programs/meson.build
  lib/common/pool.c
  lib/common/pool.h
  programs/fileio.c
  programs/fileio.h
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#2985 ZSTD CLI: Use buffered output
  programs/fileio.c
Labels: CLA Signed

#3005 Use faster Python script to amalgamate
  build/single_file_libs/README.md
  build/single_file_libs/build_library_test.sh
  build/single_file_libs/combine.py
  build/single_file_libs/combine.sh
  build/single_file_libs/create_single_file_decoder.sh
  build/single_file_libs/create_single_file_library.sh
  build/single_file_libs/zstd-in.c
  build/single_file_libs/zstddeclib-in.c
Labels: CLA Signed

#2909 Change zstdless behavior to align with zless
  programs/zstdless
  tests/playTests.sh
Labels: CLA Signed

#3026 cleanup double word in comment.
  lib/zstd.h
Labels: CLA Signed

#3021 AsyncIO compression part 1 - refactor of existing asyncio code
  build/VS2008/zstd/zstd.vcproj
  build/VS2010/zstd/zstd.vcxproj
  build/cmake/programs/CMakeLists.txt
  build/meson/programs/meson.build
  contrib/VS2005/zstd/zstd.vcproj
  programs/Makefile
  programs/fileio.c
  programs/fileio.h
  programs/fileio_asyncio.c
  programs/fileio_asyncio.h
  programs/fileio_common.h
  programs/fileio_types.h
Labels: CLA Signed

#2965 Converge sumtype (offset | repcode) numeric representation towards offBase
  contrib/seekable_format/zstdseek_decompress.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_compress_superblock.c
  lib/compress/zstd_double_fast.c
  lib/compress/zstd_fast.c
  lib/compress/zstd_lazy.c
  lib/compress/zstd_ldm.c
  lib/compress/zstd_opt.c
  tests/decodecorpus.c
  tests/fuzzer.c
  tests/regression/.gitignore
Labels: CLA Signed

#3023 fix sequence compression API in Explicit Delimiter mode
  lib/common/error_private.c
  lib/compress/zstd_compress.c
  lib/zstd.h
  tests/fuzz/sequence_compression_api.c
  tests/fuzzer.c
Labels: CLA Signed

#3019 More traces to improved debugging of literals compression
  doc/zstd_manual.html
  lib/common/zstd_internal.h
  lib/compress/huf_compress.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_compress_literals.c
  lib/compress/zstd_cwksp.h
  lib/decompress/zstd_ddict.c
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_block.c
  lib/decompress/zstd_decompress_internal.h
  lib/legacy/zstd_v05.c
  lib/legacy/zstd_v06.c
  lib/legacy/zstd_v07.c
  lib/zstd.h
Labels: CLA Signed

#2974 Lazy parameters adaptation (part 1 - ZSTD_c_stableInBuffer)
  lib/common/error_private.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/zstd.h
  lib/zstd_errors.h
  tests/fuzzer.c
  tests/zstreamtest.c
Labels: CLA Signed

#3033 fix issue 44108
  lib/compress/zstd_compress.c
Labels: CLA Signed

#3034 fix 44122 test error
  tests/fuzz/sequence_compression_api.c
Labels: CLA Signed

#3030 Print zlib/lz4/lzma library versions in verbose version output
  programs/fileio.c
  programs/fileio.h
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#3027 fix for -r on empty directory
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed

#3020 Add new CLI testing platform
  lib/common/fse.h
  lib/common/fse_decompress.c
  programs/dibio.c
  programs/zstdcli.c
  tests/Makefile
  tests/cli-tests/.gitignore
  tests/cli-tests/README.md
  tests/cli-tests/basic/help.sh
  tests/cli-tests/basic/help.sh.stdout.glob
  tests/cli-tests/basic/version.sh
  tests/cli-tests/basic/version.sh.stdout.glob
  tests/cli-tests/bin/cmp_size
  tests/cli-tests/bin/datagen
  tests/cli-tests/bin/die
  tests/cli-tests/bin/println
  tests/cli-tests/bin/unzstd
  tests/cli-tests/bin/zstd
  tests/cli-tests/bin/zstdcat
  tests/cli-tests/bin/zstdgrep
  tests/cli-tests/common/format.sh
  tests/cli-tests/common/mtime.sh
  tests/cli-tests/common/permissions.sh
  tests/cli-tests/common/platform.sh
  tests/cli-tests/compression/adapt.sh
  tests/cli-tests/compression/basic.sh
  tests/cli-tests/compression/compress-literals.sh
  tests/cli-tests/compression/format.sh
  tests/cli-tests/compression/levels.sh
  tests/cli-tests/compression/levels.sh.stderr.exact
  tests/cli-tests/compression/long-distance-matcher.sh
  tests/cli-tests/compression/multi-threaded.sh
  tests/cli-tests/compression/row-match-finder.sh
  tests/cli-tests/compression/setup
  tests/cli-tests/compression/stream-size.sh
  tests/cli-tests/dict-builder/no-inputs.sh
  tests/cli-tests/dict-builder/no-inputs.sh.exit
  tests/cli-tests/dict-builder/no-inputs.sh.stderr.exact
  tests/cli-tests/dictionaries/dictionary-mismatch.sh
  tests/cli-tests/dictionaries/dictionary-mismatch.sh.stderr.exact
  tests/cli-tests/dictionaries/setup
  tests/cli-tests/dictionaries/setup_once
  tests/cli-tests/run.py
  tests/datagencli.c
Labels: CLA Signed

#3022 AsyncIO compression part 2 - added async read and asyncio to compression code
  programs/README.md
  programs/fileio.c
  programs/fileio_asyncio.c
  programs/fileio_asyncio.h
  programs/fileio_common.h
  programs/fileio_types.h
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed
