Repository facebook/zstd, pull requests merged in 2022-06, with the labels that each got.

#3147 fix leaking thread handles on Windows
  lib/common/threading.c
Labels: CLA Signed

#3154 Remove expensive assert in --rsyncable hot loop
  lib/compress/zstdmt_compress.c
Labels: CLA Signed

#3157 Bugfix for huge dictionaries
  lib/compress/zstd_compress.c
Labels: bug, CLA Signed

#3145 common: apply two stage copy to aarch64
  lib/common/zstd_internal.h
Labels: CLA Signed

#3141 dec: adjust seqSymbol load on aarch64
  lib/decompress/zstd_decompress_block.c
Labels: CLA Signed

#3161 [contrib] largeNbDicts bugfix + improvements
  contrib/largeNbDicts/largeNbDicts.c
Labels: CLA Signed

#3166 display a warning message when using C90 clock_t
  programs/benchzstd.c
  programs/timefn.h
Labels: CLA Signed

#3167 remove explicit standard setting from cmake script
  build/cmake/CMakeModules/AddZstdCompilationFlags.cmake
Labels: CLA Signed

#3170 removed gnu99 statement from meson recipe
  build/meson/meson.build
Labels: CLA Signed

#3152 "Short cache" optimization for level 1-4 DMS (+5-30% compression speed)
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_double_fast.c
  lib/compress/zstd_double_fast.h
  lib/compress/zstd_fast.c
  lib/compress/zstd_fast.h
  lib/compress/zstd_ldm.c
Labels: CLA Signed, optimization

#3175 Streaming decompression can detect incorrect header ID sooner
  lib/decompress/zstd_decompress.c
  tests/zstreamtest.c
Labels: CLA Signed

#3177 Add prefetchCDictTables CCtxParam (+10-20% cold dict compression speed)
  contrib/largeNbDicts/largeNbDicts.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_double_fast.c
  lib/compress/zstd_fast.c
  lib/zstd.h
  tests/fuzz/zstd_helpers.c
  tests/fuzzer.c
Labels: CLA Signed, optimization

#3179 Prepare v1.5.3
  CHANGELOG
  doc/zstd_manual.html
  lib/zstd.h
  programs/zstd.1
Labels: CLA Signed, release-blocking
