Repository facebook/zstd, pull requests merged in 2022-05, with the labels that each got.

#3122 meson: for internal linkage, link to both libzstd and a static copy of it
  build/meson/lib/meson.build
  build/meson/programs/meson.build
  build/meson/tests/meson.build
Labels: CLA Signed

#3126 Unbreak FreeBSD CI
  .cirrus.yml
Labels: CLA Signed

#3129 ZSTD_fast_noDict: Avoid Safety Check When Writing `ip1` into Table
  lib/compress/zstd_fast.c
  tests/regression/results.csv
Labels: CLA Signed, optimization

#3127 Correct and clarify repcode offset history logic
  lib/compress/zstd_double_fast.c
  lib/compress/zstd_fast.c
  lib/compress/zstd_lazy.c
Labels: bug, CLA Signed

#3135 Typo in man
  programs/zstd.1
  programs/zstd.1.md
Labels: CLA Signed

#3136 Add Racket binding
  index.html
Labels: CLA Signed

#3139 [lazy] Optimize ZSTD_row_getMatchMask for levels 8-10 for ARM
  lib/compress/zstd_lazy.c
Labels: CLA Signed

#3143 fix small error in format documentation example
  doc/zstd_compression_format.md
Labels: CLA Signed
