Repository facebook/zstd, pull requests merged in 2023-10, with the labels that each got.

#3777 fix x32 tests on Github CI
  .github/workflows/dev-short-tests.yml
Labels: CLA Signed, test issue

#3771 Fix new typos found by codespell
  build/cmake/lib/CMakeLists.txt
  doc/educational_decoder/zstd_decompress.c
  doc/zstd_manual.html
  lib/common/pool.h
  lib/compress/huf_compress.c
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_cwksp.h
  lib/decompress/zstd_decompress_block.c
  lib/zstd.h
  tests/fuzz/fuzz_third_party_seq_prod.h
  tests/fuzzer.c
  tests/zstreamtest.c
Labels: CLA Signed

#3772 Do not test WIN32, instead test _WIN32
  contrib/seekable_format/examples/parallel_processing.c
  programs/fileio.c
  programs/platform.h
  programs/util.h
  zlibWrapper/examples/minigzip.c
Labels: CLA Signed

#3763 Fix a very small formatting typo in the lib/README.md file
  lib/README.md
Labels: CLA Signed

#3752 Fix pzstd Makefile to allow setting `DESTDIR` and `BINDIR` separately
  contrib/pzstd/Makefile
Labels: CLA Signed

#3786 Remove FlexArray pattern from ZSTDMT
  lib/compress/zstd_compress.c
  lib/compress/zstdmt_compress.c
  tests/fuzzer.c
Labels: CLA Signed

#3789 solving flexArray issue #3785 in fse
  lib/common/fse.h
  lib/common/fse_decompress.c
  lib/compress/fse_compress.c
Labels: CLA Signed

#3795 Add doc on how to use it with cmake FetchContent
  build/cmake/README.md
Labels: CLA Signed, build
