Repository facebook/zstd, pull requests merged in 2023-11, with the labels that each got.

#3806 Correct FSE probability bit consumption in specification
  doc/zstd_compression_format.md
Labels: CLA Signed, documentation

#3812 Add Bazel module instructions to README.md
  README.md
Labels: CLA Signed, build, documentation

#3813 Clarify that a stream containing too many Huffman weights is invalid
  doc/zstd_compression_format.md
Labels: CLA Signed, documentation

#3807 [cmake] Require CMake version 3.5 or newer
  build/cmake/CMakeLists.txt
Labels: CLA Signed, build

#3826 [huf] Improve fast huffman decoding speed in linux kernel
  lib/README.md
  lib/decompress/huf_decompress.c
Labels: CLA Signed

#3820 update xxhash library to v0.8.2
  lib/common/xxhash.c
  lib/common/xxhash.h
Labels: CLA Signed

#3831 Modernize macros to use `do { } while (0)`
  lib/common/compiler.h
  lib/common/debug.h
  lib/common/error_private.h
  lib/common/zstd_internal.h
  lib/compress/zstd_compress.c
  lib/compress/zstd_double_fast.c
  lib/compress/zstd_fast.c
  lib/compress/zstd_opt.c
  lib/compress/zstdmt_compress.c
  lib/decompress/huf_decompress.c
  lib/decompress/zstd_decompress.c
  lib/dictBuilder/zdict.c
Labels: CLA Signed

#3814 Clarify that the presence of weight value 1 is required, and a lone implied 1 weight is invalid
  doc/zstd_compression_format.md
Labels: CLA Signed, documentation

#3839 Move offload API params into ZSTD_CCtx_params
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/zstd.h
Labels: CLA Signed
