Repository facebook/zstd, pull requests merged in 2023-05, with the labels that each got.

#3623 Allow Build-Time Exclusion of Individual Compression Strategies
  .github/workflows/dev-short-tests.yml
  lib/README.md
  lib/compress/zstd_compress.c
  lib/compress/zstd_double_fast.c
  lib/compress/zstd_double_fast.h
  lib/compress/zstd_lazy.c
  lib/compress/zstd_lazy.h
  lib/compress/zstd_ldm.c
  lib/compress/zstd_opt.c
  lib/compress/zstd_opt.h
  lib/libzstd.mk
  tests/fuzzer.c
  tests/playTests.sh
Labels: enhancement, CLA Signed, build issue

#3636 Get zstd working with ARM64EC on Windows
  lib/common/compiler.h
  lib/common/xxhash.h
Labels: CLA Signed

#3631 minor : update streaming_compression example
  examples/streaming_compression.c
Labels: CLA Signed

#3658 Fix UBSAN issue (zero addition to NULL)
  lib/compress/zstd_compress.c
Labels: CLA Signed

#3657 Add options in Makefile to cmake
  build/cmake/lib/CMakeLists.txt
Labels: CLA Signed, build
