Repository facebook/zstd, pull requests merged in 2025-01, with the labels that each got.

#4228 ZSTD_getFrameHeader() for skippable frames
  contrib/linux-kernel/linux_zstd.h
  doc/zstd_manual.html
  lib/common/zstd_trace.h
  lib/decompress/zstd_decompress.c
  lib/decompress/zstd_decompress_internal.h
  lib/zstd.h
  programs/fileio.c
  tests/fuzz/simple_round_trip.c
  tests/fuzz/zstd_frame_info.c
  tests/fuzzer.c
  tests/zstreamtest.c
Labels: CLA Signed

#4229 Support for libc variants without fseeko/ftello
  build/cmake/CMakeLists.txt
  contrib/seekable_format/zstdseek_decompress.c
  programs/fileio_common.h
  programs/util.h
Labels: CLA Signed

#4223 [opt] Fix too short of match getting generated
  lib/compress/zstd_compress.c
  lib/compress/zstd_opt.c
Labels: CLA Signed

#4230 Do not vary row matchfinder selection based on availability of SSE2/Neon
  lib/compress/zstd_compress.c
Labels: CLA Signed

#4231 Update MANDIR for FreeBSD
  programs/Makefile
Labels: CLA Signed

#4218 Move #includes out of `extern "C"` blocks
  contrib/pzstd/test/PzstdTest.cpp
  contrib/pzstd/test/RoundTripTest.cpp
  contrib/seekable_format/zstd_seekable.h
  lib/common/bitstream.h
  lib/common/debug.h
  lib/common/error_private.h
  lib/common/fse.h
  lib/common/huf.h
  lib/common/mem.h
  lib/common/pool.h
  lib/common/threading.h
  lib/common/xxhash.h
  lib/common/zstd_internal.h
  lib/common/zstd_trace.h
  lib/compress/zstd_compress_internal.h
  lib/compress/zstd_cwksp.h
  lib/compress/zstd_double_fast.h
  lib/compress/zstd_fast.h
  lib/compress/zstd_lazy.h
  lib/compress/zstd_ldm.h
  lib/compress/zstd_opt.h
  lib/compress/zstd_preSplit.h
  lib/compress/zstdmt_compress.h
  lib/dictBuilder/divsufsort.h
  lib/zdict.h
  lib/zstd.h
  programs/benchfn.h
  programs/benchzstd.h
  programs/datagen.h
  programs/fileio.h
  programs/fileio_asyncio.h
  programs/fileio_common.h
  programs/platform.h
  programs/timefn.h
  programs/util.c
  programs/util.h
  zlibWrapper/zstd_zlibwrapper.h
Labels: CLA Signed

#4080 [contrib/pzstd] Prevent hangs when there are errors
  contrib/pzstd/Pzstd.cpp
  contrib/pzstd/utils/WorkQueue.h
Labels: CLA Signed

#4237 fixed an obvious macro name typo
  programs/platform.h
Labels: CLA Signed

#4234 [MSVC] Wrong define checked when building for 64bit with Visual Studio
  lib/common/bitstream.h
Labels: CLA Signed

#4232 Improve speed of ZSTD_compressSequencesAndLiterals() using AVX2
  lib/common/compiler.h
  lib/compress/zstd_compress.c
  lib/compress/zstd_compress_internal.h
  lib/zstd.h
  tests/Makefile
  tests/fullbench.c
Labels: CLA Signed

#4238 fix out-of-bounds array index access
  lib/compress/zstd_compress.c
Labels: CLA Signed

#4235 benchmark mode specifies nb of threads with -v
  programs/zstdcli.c
Labels: CLA Signed

#4242 add prerelease option
  build/VS_scripts/build.VSPreview.cmd
  build/VS_scripts/build.generic.cmd
Labels: CLA Signed, build, target specific

#4247 Added a human-readable final success message at end of tests
  .cirrus.yml
  .github/workflows/commit.yml
  .github/workflows/dev-short-tests.yml
  CONTRIBUTING.md
  Makefile
  tests/Makefile
  tests/playTests.sh
Labels: CLA Signed, test issue

#4249 minor: assert that state is not null
  lib/decompress/zstd_decompress.c
Labels: CLA Signed

#4246 [asm] Enable x86_64 asm for windows builds
  lib/common/portability_macros.h
  lib/decompress/huf_decompress_amd64.S
Labels: CLA Signed

#4248 Use _bzhi_u32 for 32-bit builds when building with STATIC_BMI2
  lib/common/bitstream.h
Labels: CLA Signed

#4250 added a CI test for x86 32-bit + avx2 combination
  .github/workflows/dev-short-tests.yml
  lib/common/bitstream.h
  lib/common/compiler.h
  lib/compress/zstd_compress.c
Labels: CLA Signed

#4251 BMI2 detection in 32-bit mode
  lib/README.md
  lib/common/compiler.h
Labels: CLA Signed

#4252 enable DYNAMIC_BMI2 by default on x86 (32-bit mode)
  lib/common/portability_macros.h
Labels: CLA Signed

#4253 minor: use BitContainerType when appropriate
  lib/common/bitstream.h
  lib/common/fse.h
Labels: CLA Signed

#4259 Add support for Apple framework builds
  .gitignore
  build/cmake/CMakeLists.txt
  build/cmake/README.md
  build/cmake/lib/CMakeLists.txt
Labels: CLA Signed, build

#4258 Implement ZSTD_ALIGNED for ms compiler
  lib/common/compiler.h
Labels: CLA Signed

#4257 Use _M_X64 only without mixing with _M_AMD64
  lib/common/compiler.h
  lib/common/mem.h
  lib/common/xxhash.h
Labels: CLA Signed

#4263 Check `DYNAMIC_BMI2` instead of `DYNAMIC_BMI2 != 0`
  lib/decompress/zstd_decompress_internal.h
Labels: CLA Signed

#4260 [linux] Expose ZSTD_compressSequences*() in the kernel
  contrib/linux-kernel/linux.mk
  contrib/linux-kernel/linux_zstd.h
  contrib/linux-kernel/mem.h
  contrib/linux-kernel/test/include/linux/unaligned.h
  contrib/linux-kernel/test/include/linux/xxhash.h
  contrib/linux-kernel/zstd_compress_module.c
Labels: CLA Signed

#4269 fix: quote include directory for resource compiler
  .github/workflows/dev-short-tests.yml
  build/cmake/lib/CMakeLists.txt
Labels: CLA Signed

#4264 Move STATIC_BMI2 define to portability_macros.h
  lib/common/compiler.h
  lib/common/portability_macros.h
Labels: CLA Signed

#4278 bench: better result alignment
  programs/benchzstd.c
Labels: CLA Signed

#4271 cmake: Remove duplicated line
  build/cmake/lib/CMakeLists.txt
Labels: CLA Signed

#4265 Check `STATIC_BMI2` instead of `STATIC_BMI2 == 1`
  lib/common/bits.h
  lib/common/bitstream.h
Labels: CLA Signed
