Repository facebook/zstd, pull requests merged in 2025-02, with the labels that each got.

#4286 Fix Visual + ClangCL + AVX2 compilation
  .github/workflows/dev-short-tests.yml
  lib/common/compiler.h
Labels: CLA Signed

#4287 visual studio compilation tests: error out on warnings
  .github/workflows/dev-short-tests.yml
  lib/compress/zstd_compress.c
  tests/fullbench.c
  tests/fuzzer.c
  tests/zstreamtest.c
Labels: CLA Signed

#4276 fix speed of --patch-from mode at high compression levels
  .github/workflows/dev-long-tests.yml
  Makefile
  lib/compress/zstd_compress.c
  lib/compress/zstdmt_compress.c
  tests/regression/results.csv
Labels: CLA Signed

#4284 Add noexecstack flag for gcc/clang C and CPP in Meson
  build/meson/meson.build
Labels: CLA Signed

#4290 --max command
  programs/zstd.1.md
  programs/zstdcli.c
  tests/cli-tests/compression/levels.sh
  tests/cli-tests/compression/levels.sh.stderr.exact
Labels: CLA Signed

#4289 --ultra automatically triggered with --long and --patch-from
  programs/zstdcli.c
Labels: CLA Signed

#4288 Improve compression ratio of the --patch-from mode
  lib/compress/zstd_ldm.c
  programs/fileio.c
  programs/zstd.1.md
  tests/regression/results.csv
Labels: CLA Signed

#4293 Fixed CI
  .cirrus.yml
  .github/workflows/dev-short-tests.yml
Labels: CLA Signed, test issue

#4274 CI: enable Intel LLVM C compiler (icx) check
  .github/workflows/dev-short-tests.yml
Labels: CLA Signed

#4297 update changelog for v1.5.7
  CHANGELOG
Labels: CLA Signed

#4299 Improved Github Actions scorecards
  .github/workflows/android-ndk-build.yml
  .github/workflows/dev-short-tests.yml
Labels: CLA Signed

#4300 updated benchmark numbers for v1.5.7
  README.md
Labels: CLA Signed

#4302 updated man pages and manual
  doc/zstd_manual.html
  programs/zstd.1
  programs/zstdgrep.1
  programs/zstdless.1
Labels: CLA Signed

#4309 Check API manual and man pages before release
  .github/workflows/dev-short-tests.yml
  .github/workflows/release_check.yml
Labels: CLA Signed

#4310 [cmake] use target_compile_definitions
  build/cmake/lib/CMakeLists.txt
Labels: CLA Signed

#4319 step towards -Wconversion
  lib/common/bits.h
  lib/common/compiler.h
  lib/common/zstd_internal.h
  lib/compress/zstd_compress_internal.h
  lib/decompress/huf_decompress.c
  lib/decompress/zstd_decompress_block.c
  lib/dictBuilder/cover.c
  lib/dictBuilder/divsufsort.c
  lib/dictBuilder/zdict.c
Labels: CLA Signed

#4320 build_package.bat: fix path to zstd_errors.h, avoid silently ignore of the errors if build failed
  .github/workflows/windows-artifacts.yml
  lib/dll/example/build_package.bat
Labels: CLA Signed, packaging issue

#4317 Fix function signature mismatch for ZSTD_convertBlockSequences
  lib/compress/zstd_compress_internal.h
Labels: CLA Signed

#4312 introduce ZSTD_USE_C90_QSORT
  .github/workflows/dev-short-tests.yml
  lib/README.md
  lib/dictBuilder/cover.c
Labels: CLA Signed

#4322 fix the meson windows build
  contrib/pzstd/Logging.h
Labels: CLA Signed

#4321 Automate Windows Artifact generation and publication
  .github/workflows/windows-artifacts.yml
  lib/dll/example/build_package.bat
Labels: CLA Signed

#4323 Backport patches from Linux Kernel
  contrib/linux-kernel/linux_zstd.h
  contrib/linux-kernel/zstd_compress_module.c
  contrib/linux-kernel/zstd_decompress_module.c
Labels: CLA Signed
