Repository facebook/zstd, pull requests merged in 2025-03, with the labels that each got.

#4327 Generate Zstandard binaries for Windows with lz4 support
  .github/workflows/windows-artifacts.yml
Labels: CLA Signed

#4329 New commands --split and --jobsize
  programs/benchzstd.c
  programs/benchzstd.h
  programs/dibio.c
  programs/fileio.c
  programs/fileio.h
  programs/fileio_types.h
  programs/zstd.1.md
  programs/zstdcli.c
  tests/cli-tests/compression/multi-threaded.sh
  tests/cli-tests/compression/multi-threaded.sh.stderr.exact
  tests/cli-tests/dict-builder/no-inputs.sh.stderr.exact
  tests/playTests.sh
Labels: CLA Signed

#4335 warn when requesting decompression with multiple threads
  programs/zstdcli.c
  tests/cli-tests/compression/multi-threaded.sh
  tests/cli-tests/compression/multi-threaded.sh.stderr.exact
Labels: CLA Signed

#4338 [linux] Opt out of row based match finder for the kernel
  lib/compress/zstd_compress.c
Labels: CLA Signed

#4336 fix #4312 - musl compilation compatibility
  .github/workflows/dev-short-tests.yml
  lib/README.md
  lib/dictBuilder/cover.c
  tests/playTests.sh
Labels: CLA Signed

#4341 lib/zstd.h: don't put pragma after static
  lib/zstd.h
Labels: CLA Signed

#4344 add an assert
  lib/compress/huf_compress.c
Labels: CLA Signed

#4345 [doc] minor clarification for maximum block size
  doc/zstd_compression_format.md
Labels: CLA Signed, documentation

#4350 add --patch-apply command
  programs/zstdcli.c
  tests/playTests.sh
Labels: CLA Signed, feature request

#4346 fix a risk of overflow on a time counter on Windows
  programs/timefn.c
Labels: CLA Signed

#4349 Support process substitution for `--filelist=`
  .github/workflows/dev-long-tests.yml
  programs/fileio.c
  programs/util.c
  programs/util.h
  programs/zstdcli.c
  tests/cli-tests/file-stat/compress-file-to-dir-without-write-perm.sh.stderr.exact
  tests/playTests.sh
  tests/test_process_substitution.bash
Labels: CLA Signed, feature request
